In [1]:
import numpy as np

In [4]:
data = np.loadtxt("../data/movielens-1m/ratings.dat", delimiter="::",dtype=np.int64)

In [5]:
print(data[:5, :])
print(data.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
(1000209, 4)


## <전체 평균 평점 계산하기>

In [8]:
mean_rating_total = data[:,2].mean()
mean_rating_total

3.581564453029317

## <각 사용자 별 평균 평점 계산하기>
- 전체데이터 중 기준으로 삼을 열만 인덱싱하여 전체데이터에 대한 전체기준열 array로 삼을 것이다.
- 기준으로 삼은 열에서 unique(arr)함수로 중복없는 기준열array변수에 따로 담아놓자.
- 전체 기준열array == 중복없는 기준열array 중 특정성분을 조건문으로 하여 마스크를 만든다.
- 그 마스크를 전체데이터의 행의 index에 집어 넣으면, 전체기준열에서 특정성분을 가진 행만을 뽑아 낼 수 있다. 열의 index에 넣으면 원하는 열만을 뽑아낼 수 있다.

중복 데이터 제거

In [6]:
user_ids = np.unique(data[:, 0])
user_ids.shape

(6040,)

상위 5개 열 확인, shape확인

In [7]:
print(user_ids[:5])
print(user_ids.shape)

[1 2 3 4 5]
(6040,)


In [10]:
mean_rating_by_user_list = []
for user_id in user_ids:
    data_for_user = data[data[:, 0] == user_id, :]
    # print(data_for_user.shape)
    mean_rating_for_user = data_for_user[:, 2].mean()
    # print(mean_rating_for_user)
    mean_rating_by_user_list.append([user_id, mean_rating_for_user])

In [11]:
mean_rating_by_user_list[:5]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]

In [15]:
mean_rating_by_user_array = np.array(mean_rating_by_user_list, dtype=np.float32)

In [13]:
print(mean_rating_by_user_array[:5])
print(mean_rating_by_user_array.shape)

[[1.         4.18867925]
 [2.         3.71317829]
 [3.         3.90196078]
 [4.         4.19047619]
 [5.         3.14646465]]
(6040, 2)


In [18]:
np.savetxt("C:\python\DataScience\data\movielens-1m/mean_rating_by_user.csv",mean_rating_by_user_array, fmt="%.3f", delimiter=",")