In [ ]:
import numpy as np

In [ ]:
np._version__

In [ ]:
data = [6, 7.5, 8, 9, 1]
arr = np.array(data)
print(type(arr), id(arr))

In [ ]:
myList = ['강아지','원숭이','꽃']
np.array(myList)

## Numpy 버전 확인

In [ ]:
# 숫자 넘파이 배열 생성하기
n1 = np.array([1,5,6,10,33])
n2 = np.array([0.5,2.0,5,45.4])
n1
n2
print(n1)
print(n2)

In [ ]:
# 문자열 넘파이 배열 생성하기
color_list = np.array(['빨강','파랑','초록'])
color_list
print(color_list.size, len(color_list), color_list.shape)

In [ ]:
# 한개의 넘파이 배열 출력시에는 for 반복문 이용
for i in color_list:
    print(i)

넘파이 배열 인덱싱
- 넘파이배열변수[] .... 못적음..

퀴즈
- animal 이라는 넘파이 배열 생성
- 구성요소는 동물 이름 [호랑이, 토끼, 곰, 거북이, 펭귄]
- 역순으로 하나씩 출력

In [ ]:
animal = np.array(['호랑이', '토끼', '곰', '거북이', '펭귄'])
animal

In [ ]:
for i in range(5):
    print(i)

In [ ]:
# 역순
n = len(animal)
for n in range(n-1,-1,-1):
    print(animal[n])

## 넘파이 배열의 속성 알아보기
- 넘파이배열변수 shape : 구조와 크기
- type(넘파이배열변수) : 객체의 형태 출력
- 넘파이배열변수 ndim : 차원
- 넘파이배열변수 dtpye : 데이터형

## 자동 데이터형 변환
- 숫자+문자 => 문자
- 정수형+실수형 => 실수형

**데이터 형 변환하기 - Casting**
- 새넘파이배열변수 = 넘파이배열변수.astype(데이터형)
- 

In [ ]:
# 정수형 넘파이 배열
a = np.array([1,2,36,10])
print(a,a.dtype)

In [ ]:
# 정수형 -> 문자형 넘파이 배열
# b = a.astype('<U2')
b = a.astype(np.str)
print(b,b.dtype)

In [ ]:
# 정수형 -> 실수형 넘파이 배열
c = a.astype(float)
print(c,c.dtype)

## 넘파이 배열 생성시 자료형 지정하기
- np.array(데이타리스트, dtype데이터자료형)
- 데이터형: float, int, '<U2' , np.str

In [ ]:
# 정수형 -> 문자형
aa = np.array([3,10,33,20], dtype=np.str)
print(aa, aa.dtype)

In [ ]:
# 실수형 -> 정수형
# 소숫점 아래 자리는 자동으로 삭제된다.
bb = np.array([3.45,5.5,45.1], dtype=int)
print(bb,bb.dtype)

## 2차원 배열 만들기
- 넘파이배열변수 = np.array([[1행...],[2행...]])
- 각 행의 데이타 갯수가 같아야 한다.

In [ ]:
np2d = np.array([[3,4,5],[6,7,8]])
np2d

In [ ]:
# 넘파이배열의 형태 확인
np2d.shape

In [ ]:
# 전체 넘파이 배열의 갯수 출력
# len(np2d)
np2d.size

In [ ]:
# 전체 차원수 확인하기
np2d.ndim

**퀴즈**
- 2행 3열의 넘파이 배열을 생성하여라 -int형
- 2행 3열의 넘파이 배열의 데이터형을 문자형으로 변경하여라 - np.str

In [ ]:
cc = np.array([[3,4,5],[10,20,20]])
cc.dtype

In [ ]:
cc_str = cc.astype(np.str)
cc_str

## 2차원 넘파이 배열 생성 후 하나씩 출력하여라

In [18]:
np2d_list = np.array([[0,45],[20,30]])
np2d_list

array([[ 0, 45],
       [20, 30]])

In [19]:
# 행으로 출력
for i in np2d_list:
    print(i)

[ 0 45]
[20 30]


In [20]:
# 각각의 원소 출력
for i in np2d_list:
    print('------------')
    for j in i:
        print(j)

------------
0
45
------------
20
30


In [27]:
# 가로로 각각의 원소 출력
for i in np2d_list:
    print('\n------')


------

------


In [21]:
np1 = np.zeros(5)
np1

array([0., 0., 0., 0., 0.])

In [25]:
np2 = np.zeros((2,2))

## 퀴즈
- 1~15로 데이타값을 갖는 넘파이 배열 3행 5열을 생성하여라
``` python
[[1,2,3,4,5],
 [6,7,8,9,10],
 [11,12,13,14,15]]
```

In [28]:
result = np.arange(1,16)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
result.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## 넘파이 배열 구조 변경하기 2
- 2차원 -> 1차원 배열로 변경
- 넘파이배열변수 flatten()

In [30]:
cc = np.array([['a','b'],['c','d']])
cc

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [31]:
cc_result = cc.flatten()
cc_result

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [34]:
sum_value = 0
for i in range(1,101):
    sum_value += i
print(sum_value)

5050


In [35]:
print(np.sum([x for x in range(1,101)]))

5050


## Numpy 배열의 행열 연산

In [ ]:
arrOne = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
arrTwo = np.array([[7,8,9],[10,11,12]], dtype=np.float64)
arrOne
arrTwo

In [ ]:
arrOne + arrTwo

In [38]:
arr2d = np.arange(1,16)
arr2d.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## 퀴즈
상위 5% 뽑기

In [47]:
large_arr=np.random.rand(50)
n = int(len(large_arr) * 0.05)
np.sort(large_arr)[::-1][0:n]

array([0.96280685, 0.95160291])

In [ ]:
# 외부파일 불러오기
data = np.loadtxt('data/ratings.dat',delimiter='::', dtype=np.int64)
data[:5,:]

In [ ]:
dicetances = 

In [ ]:
# 기본 파이썬으로 속도 계산 (거리 / 시간)
speed =[]
for i in range(len(distances)):
    speed = 

In [ ]:
# 리스트에서 numpy 배열 만들기
distance = [10,15,17,16,]