In [25]:
import numpy as np

## Numpy 버전 확인

In [26]:
np.__version__

'1.16.4'

## 넘파이 배열 만들기

- np.array(리스트)
- 숫자, 문자로 아이템 삽입

In [27]:
# 숫자 넘파이 배열 생성하기 
n1 = np.array([1,5,6,10,33])
n2 = np.array([0.5,2.0,5,45.4])
n1
n2
print(n1)
print(n2)

[ 1  5  6 10 33]
[ 0.5  2.   5.  45.4]


In [28]:
# 문자 넘파이 배열 만들기 
color_list = np.array(['빨강','파랑','초록'])
color_list
print(color_list.size, len(color_list), 
      color_list.shape)

3 3 (3,)


In [29]:
# 한개의 넘파이 배열 출력시에는 for 반복문 이용 
for i in color_list:
    print(i)

빨강
파랑
초록


## 넘파이 배열 인덱싱

- 넘파이배열변수[indexNumber]

In [30]:
n1

array([ 1,  5,  6, 10, 33])

In [31]:
n1[0]

1

In [32]:
n1[4]

33

In [33]:
n1[-1]

33

In [34]:
# 2번 인덱스 부터 추출 
n1[2:]

array([ 6, 10, 33])

In [35]:
n1[:]

array([ 1,  5,  6, 10, 33])

## 퀴즈

- animal 이라는 넘파이 배열 생성 
- 구성요소는 동물 이름 
  [호랑이, 토끼, 곰, 거북이, 펭귄]
- 역순으로 하나씩 출력
  [펭귄 거북이 곰 토끼 호랑이]

In [36]:
animal = np.array(['호랑이', '토끼', '곰', '거북이', '펭귄'])
animal

array(['호랑이', '토끼', '곰', '거북이', '펭귄'], dtype='<U3')

In [37]:
for i in range(5):
    print(i)

0
1
2
3
4


In [38]:
# range(초기,끝,증감치)
for i in range(5,0,-1):
    print(i)

5
4
3
2
1


In [39]:
for i in animal:
    print(i)

호랑이
토끼
곰
거북이
펭귄


In [40]:
# 역순 
n = len(animal)
for n in range(n-1,-1,-1):
    print(animal[n])

펭귄
거북이
곰
토끼
호랑이


## 넘파이 배열의 속성 알아보기

- 넘파이배열변수.shape : 구조와 크기
- type(넘파이배열변수) : 객체의 형태 출력
- 넘파이배열변수.ndim : 차원
- 넘파이배열변수.dtype : 데이터형

In [41]:
# 정수, 실수, 문자열 넘파이 생성 
np1 = np.array(['세종대','건국대','연세대'])
np2 = np.array([3,4,5,10])
np3 = np.array([1.4, 5.0])
print(np1, np2, np3)

['세종대' '건국대' '연세대'] [ 3  4  5 10] [1.4 5. ]


In [ ]:
print(np1, type(np1))

In [ ]:
myList = ['세종대' '건국대' '연세대']
type(myList)

In [ ]:
# .shape 넘파이 배열의 크기와 구조 
np1.shape

In [ ]:
len(np1)

In [ ]:
# .ndim : 차원 확인 
np1.ndim

In [ ]:
# .dtype : 배열의 데이타형 확인하기 
print(np1.dtype, np2.dtype, np3.dtype)

## 자동 데이터 형 변환

- 숫자 + 문자 -> 문자
- 정수형 + 실수형 -> 실수형

In [ ]:
print(np1, np1.dtype)

In [ ]:
print(np3, np3.dtype)

In [ ]:
np4 = np.array(['세종대','이화여대',34, 6.7])
np4

In [ ]:
np4.dtype

In [ ]:
np5 = np.array([4, 5, 5.5])
np5

In [ ]:
np5.dtype

## 데이터 형 변환하기 - Casting

- 새넘파이배열변수 = 넘파이배열이름.astype(데이터형)
- 데이터형 : float, int, '<U2', np.str

In [42]:
# 정수형 넘파이 배열 
a = np.array([1,2,36,10])
print(a, a.dtype)

[ 1  2 36 10] int32


In [ ]:
# 정수형 -> 문자형 넘파이 배열 
# b = a.astype('<U2')
b = a.astype(np.str)
print(b, b.dtype)

In [ ]:
# 정수형 ->  실수형 넘파이 배열 
c = a.astype(float)
print(c, c.dtype)

In [43]:
num = 32434234234234234234
print(num, type(num))

32434234234234234234 <class 'int'>


## 넘파이 배열 생성시 자료형 지정하기

- np.array(데이타리스트, dtype=데이타자료형)
- 데이터형 : float, int, '<U2', np.str

In [44]:
# 정수형 -> 문자형 
aa = np.array([3, 10, 33, 20],dtype=np.str)
print(aa, aa.dtype)

['3' '10' '33' '20'] <U2


In [45]:
# 실수형 -> 정수형 
# 소숫점 아래 자리는 자동으로 삭제된다. 
bb = np.array([3.45, 5.5, 45.1],dtype=int)
print(bb, bb.dtype)

[ 3  5 45] int32


## 2차원 배열 만들기

- 넘파이배열변수 = np.array([[1행...],[2행...]])
- 각 행의 데이타 갯수가 같아야 한다.

In [46]:
np2d = np.array([[3,4,5],[6,7,8]])
np2d 

array([[3, 4, 5],
       [6, 7, 8]])

In [47]:
# 넘파이배열의 형태 확인 
np2d.shape

(2, 3)

In [ ]:
# 전체 넘파이 배열의 갯수 출력 
# len(np2d)
np2d.size

In [ ]:
# 전체 차원수 확인하기 
np2d.ndim

## 퀴즈

- 2행 3열의 넘파이 배열을 생성하여라 - int 형 
- 2행 3열의 넘파이 배열의 데이타형을 문자형으로 변경하여라 - np.str

In [ ]:
cc = np.array([[3,4,5],[10,20,20]])
cc.dtype

In [ ]:
cc_str = cc.astype(np.str)
cc_str

## 2차원 넘파이 배열 생성 후 하나씩 출력하여라

In [48]:
np2d_list = np.array([[0,45],[20,30]])
np2d_list

array([[ 0, 45],
       [20, 30]])

In [49]:
# 행으로 출력 
for i in np2d_list:
    print(i)

[ 0 45]
[20 30]


In [ ]:
# 각각의 원소 출력 
for i in np2d_list:
    print('---------')
    for j in i:
        print(j)

In [ ]:
# 각각의 가로로 원소 출력 
for i in np2d_list:
    print('\n---------')
    for j in i:
        print(j, end='  ')

## 0또는 1로 데이터 입력해서 넘파이 배열 만들기

- np.zeros(데이타갯수) : 1차
- np.zeros((행수,열수)) : 2차
- np.ones(데이타갯수) : 1차
- np.ones((행수,열수)) : 2차

In [50]:
np1 = np.zeros(5)
np1

array([0., 0., 0., 0., 0.])

In [51]:
np2 = np.zeros((2,2))
np2

array([[0., 0.],
       [0., 0.]])

In [52]:
np3 = np.ones(5)
np4 = np.ones((3,3))
print(np3,'\n\n', np4)

[1. 1. 1. 1. 1.] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 자동으로 숫자 데이터 채워 넘파이 배열 만들기

- np.arange(숫자)
- np.arange(start, end-1)
- np.arange(start, end-1, step)

In [ ]:
n1 = np.arange(5)
n1

In [ ]:
n2 = np.arange(1,8)
n2

In [ ]:
n3 = np.arange(1,10,2)
n3

## 넘파이 배열 구조 변경하기 1

- 1차원 -> 2차원 배열로 변경
- 넘파이배열변수.reshape(행수,열수)

In [ ]:
a = np.array([3, 10, 40, 100])
a

In [ ]:
a.reshape(2,2)

## 퀴즈

- 1~15로 데이터값을 갖는 넘파이 배열 3행 5열로 생성하여라

```python
[[1,2,3,4,5],
 [6,7,8,9,10],
 [11,12,13,14,15]]
```

In [54]:
result = np.arange(1,16)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
result.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## 넘파이 배열 구조 변경하기 2

- 2차원 -> 1차원 배열로 변경
- 넘파이배열변수.flatten()

In [56]:
cc = np.array([['a','b'],['c','d']])
cc

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [57]:
cc_result = cc.flatten()
cc_result

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [58]:
sum_value = 0
for i in range(1, 101):
    sum_value += i
print(sum_value)

5050


In [59]:
print(np.sum([x for x in range(1, 101)]))

5050


In [60]:
large_arr = np.random.randn(50) 
n = int(len(large_arr)*0.05)
np.sort(large_arr)[::-1][0:n]

array([2.82722392, 1.5185021 ])

## 넘파이 배열의 연산

- 덧셈
- 뺄셈
- 곱셈

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[10,2],[34,10]])

In [ ]:
print(x, '\n\n', y)

In [ ]:
x + y

In [ ]:
x - y

In [ ]:
# 수학시간의 행열 연산이 아니고 같은 위치의 데이타가 곱해진다.
x * y

In [ ]:
x*5

In [ ]:
x/2

In [ ]:
x ** 2

## 넘파이 배열의 데이타 교체

In [ ]:
subject = np.array(['국어','영어', '수학', '과학'])
subject

In [ ]:
# 0 번째 데이타 교체 
subject[0] = '코딩'
subject

## 퀴즈

- 10, 20 ~ 100 까지 10개로 구성된 넘파이 배열을 생성한다. 
- 인덱스가 2~5까지 구성되어 있는 데이타값을 0으로 교체한다. 

```python
[ 10, 20, 30, 40 ... 100]
->
[ 10, 20, 0, 0, 0, 0, 70, 80, 90, 100]
```

In [ ]:
q = np.arange(10, 101, 10)
q

In [ ]:
q[2:6]= 0
q

## :: 를 이용한 인덱싱

- 넘파이배열변수[start:end+1:step]

In [ ]:
z = np.arange(1,11)
z

In [ ]:
# 0~2 번 인덱스까지 추출 
z[0:3]

In [ ]:
# 홀수번째 출력 
z[0:10:2]

In [ ]:
# 특정 인덱스 출력 
z[0:10:3]

In [ ]:
z[::2]

## 2차원 넘파이 인덱싱

In [ ]:
arr1 = np.arange(15)
arr1 = arr1.reshape(3,5)
arr1

In [ ]:
# 1행만 추출하기 
arr1[0]

In [ ]:
arr1[0, :]

In [ ]:
# 1열만 추출하기 
arr1[:, 0]

In [ ]:
# 홀수번째 행만 추출하기 
arr1[::2,:]

In [ ]:
arr1

In [ ]:
# 홀수번째 열로 구성된 데이타 추출 
arr1[:,::2]

In [ ]:
# 마지막 행의 마지막 열 인덱스 
arr1[-1,-1]

In [ ]:
arr1[0:2,0:2]

In [ ]:
arr1[0:2,2:4]

## 난수 생성하기

- np.random.randn(데이터갯수) : 1차원 실수형
- np.random.randn(행수,열수) : 2차원 실수형
- np.random.randint(숫자) : 0~숫자까지의 양수.
- np.random.randint(start, end) : start숫자 ~ end-1숫자까지의 정수

In [ ]:
r1 = np.random.randn(10)
r1

In [ ]:
r2 = np.random.randn(4,4)
r2

In [ ]:
# 0 ~ 9 사이의 정수 난수 1개 추출 
r3 = np.random.randint(10)
r3

In [ ]:
r3 = np.random.randint(-20,20)
r3

## 합계와 평균

- 넘파이배열변수.sum()
- 넘파이배열변수.mean()

In [ ]:
n1 = np.arange(1,11)
n1

In [ ]:
n1.sum()

In [ ]:
n1.mean()

## 2차원 넘파이 배열의 합

- 넘파이배열변수.sum(axis=0) : 각 열의 합
- 넘파이배열변수.sum(axis=1) : 각 행의 합
- 넘파이배열변수.mean(axis=0) : 각 열의 평균
- 넘파이배열변수.mean(axis=1) : 각 행의 평균

In [ ]:
n2 = np.arange(1,13)
n2 = n2.reshape(3,4)
n2

In [ ]:
# 각 열의 합
n2.sum(axis=0)

In [ ]:
# 각 행의 합
n2.sum(axis=1)

In [ ]:
# 각 열의 평균
n2.mean(axis=0)

In [ ]:
# 각 행의 평균
n2.mean(axis=1)

## 두 넘파이 배열에서 크거나 작은 숫자만 추출하기

- np.maximum(배열1,배열2)
- np.minimum(배열1,배열2)

In [ ]:
x = np.arange(1,5)
y = np.arange(4,8)
print(x, '\n\n', y)

In [ ]:
np.maximum(x,y)

In [ ]:
# 난수 배열 생성하기 
x1 = np.random.randn(10)
y1 = np.random.randn(10)
print(x1, '\n\n', y1)

In [ ]:
np.maximum(x1,y1)

In [ ]:
np.minimum(x1,y1)

## Numpy 배열의 병합( concatenate)

- np.vstack((배열명1,배열명2)) : 행으로 합치기, (( ))에 유의
- np.hstack((배열명1,배열명2)) : 열로 합치기, (( ))에 유의

In [ ]:
d = np.arange(1,11)
e = np.arange(11,21)
print(d)
print(e)

In [ ]:
arr1 = np.vstack((d,e))
arr1

In [ ]:
# 2차원으로 생성 
arr1.shape

In [ ]:
arr2 = np.hstack((d,e))
arr2

In [ ]:
# 1차로 생성 
arr2.shape

## 정렬과 관련된 함수 이용하기

- np.sort(배열이름) : 오름차순 정렬
- np.sort(배열이름)[::-1] : 내림차순 정렬, 역정렬

In [ ]:
r1 = np.random.randn(10)
r1

In [ ]:
# 오름차순 
np.sort(r1)

In [ ]:
# 내림차순 
np.sort(r1)[::-1]

## 정렬과 관련된 함수 이용하기 – 2차원

- np.sort(배열이름, axis=0) – 열방향으로 정렬하기
- np.sort(배열이름, axis=0)[::-1] – 열방향으로 정렬하기
- np.sort(배열이름, axis=1) – 행방향으로 정렬하기
- np.sort(배열이름, axis=1)[::-1] – 행방향으로 정렬하기

In [ ]:
r2 = np.random.randn(3,4)
r2

In [ ]:
np.sort(r2, axis=0)

In [ ]:
np.sort(r2, axis=1)

## 중복값 제거하기

- np.unique(배열명)

In [ ]:
# 중복 데이타가 있는 넘파이 배열 생성 
kk = np.array(['철수','영희','철수','길동','지민','지민','지민'])
kk

In [ ]:
kk_result = np.unique(kk)
kk_result

## 단위행렬(Identity) : 대각선이 1인 행렬

- np.identity(대각선숫자)
- np.identity(n=대각선숫자, dtype=데이타형)

In [ ]:
# 실수형 단위행렬 
g_arr = np.identity(3)
g_arr 

In [ ]:
# 정수형 단위 행렬 
v_arr = np.identity(5, dtype=int)
v_arr 

In [ ]:
v_arr.dtype

## Numpy 배열의 Boolean Indexing

- 다수개의 배열에서 특정 값을 추출할 때 사용한다.
- 배열이름[조건]

In [ ]:
# 조건이 되는 배열의 전체 갯수가 조건을 적용할 배열의 행수와 같아야 한다. 
data = np.random.randn(7,4)
names = np.array(['Charles','Jhon', 'Hayoung','Charles',
                  'Hayoung','Jhon','Elise'])
data

In [ ]:
names

In [ ]:
# == , != : True / False
# names 넘파이 배열에서 'Hayoung' 값과 같으면 True 를 출력 
names == 'Hayoung'

In [ ]:
# 인덱스 2, 4번이 추출 
data[names == 'Hayoung']

In [ ]:
names == 'Elise'

In [ ]:
data[names == 'Elise']

In [ ]:
# 마지막 행 제외 나머지 행 추출 
data[names != 'Elise']

# Numpy 파일 로딩과 저장

## 현재 작업폴더 확인하기

In [ ]:
import os

In [ ]:
os.getcwd()

## 넘파이에서 파일 로딩

np.loadtxt('파일경로', delimiter='구분자', dtype=데이터형)

In [ ]:
data = np.loadtxt('../data/movielens-1m/ratings.dat', delimiter='::', dtype=int)
# 데이타 구조 확인
data.shape

In [ ]:
# 5개만 추출 
# data[:5, :]
data[:5]

In [ ]:
# 2열 추출
data[:,2].shape

In [ ]:
# 평균 구하기
data_mean = data[:,2].mean()
data_mean

In [ ]:
# 소숫점 2째자리까지만 출력하기
print('평균 : %.2f' % data_mean)

## 텍스트 파일로 저장하기

np.savetxt(fileURL, dataVar, fmt=format형식(%.3f)', delimiter=구분자)

In [ ]:
## 외부 파일 저장하기
data2 = data[:10]
data2

In [ ]:
np.savetxt("../output/ratings_data.csv", data2, fmt='%.3f', delimiter=",")